setono_sylius_abandoned_cart_shop_unsubscribe_customer:
    path: /abandoned-cart/unsubscribe
    methods: [GET,POST]
    defaults:
        _controller: Setono\SyliusAbandonedCartPlugin\Controller\Action\UnsubscribeCustomerAction
