setono_sylius_abandoned_cart_shop_unsubscribe_customer:
    path: /abandoned-cart/unsubscribe
    methods: [GET,POST]
    defaults:
        _controller: Setono\SyliusAbandonedCartPlugin\Controller\Action\UnsubscribeCustomerAction

setono_sylius_abandoned_cart_shop_recover_cart:
    path: /recover-cart/{tokenValue}
    methods: [GET]
    defaults:
        _controller: Setono\SyliusAbandonedCartPlugin\Controller\Action\RecoverCartAction
